import "./globals.css";

export const metadata = {
  title: 'Resnet-50 Inference',
  description: 'Generated by Next.js',
}

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body className="p-0 m-0">{children}</body>
    </html>
  )
}
